# Generated by Django 3.2.8 on 2022-06-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('cedula', models.IntegerField()),
                ('telefono', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=150)),
                ('profesion', models.CharField(max_length=150)),
                ('residencia', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('habilidades', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=150)),
            ],
        ),
    ]
