# Generated by Django 3.2.8 on 2022-06-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='urlmapa',
            field=models.URLField(blank=True),
        ),
    ]
