# Generated by Django 3.2.8 on 2022-06-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_urlmapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='urlmapa',
            field=models.TextField(),
        ),
    ]
